//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimesheetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects_Table()
        {
            this.Timesheets_table = new HashSet<Timesheets_table>();
        }
    
        public string Project_Name { get; set; }
        public string Client { get; set; }
        public string Project_Manager_Id { get; set; }
        public System.DateTime Deadline { get; set; }
        public Nullable<int> Technology_Id { get; set; }
        public string Member_Id { get; set; }
        public string Subtask { get; set; }
        public Nullable<bool> is_Deleted { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual Users_table Users_table { get; set; }
        public virtual Users_table Users_table1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timesheets_table> Timesheets_table { get; set; }
    }
}
