//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimesheetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technology
    {
        public int Technology_Id { get; set; }
        public string Technology_Name { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<bool> is_Deleted { get; set; }
    }
}
