//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimesheetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheets_table
    {
        public string User_Id { get; set; }
        public string Project_Name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> TimeSpent { get; set; }
        public string Wokrdone { get; set; }
        public Nullable<bool> Mode { get; set; }
        public Nullable<bool> Timesheet_Status { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<bool> is_Deleted { get; set; }
    
        public virtual Projects_Table Projects_Table { get; set; }
        public virtual Users_table Users_table { get; set; }
    }
}
